# 2. Write a program to input eight numbers from the user and display all the unique
# numbers (once).
s = set()
a = int(input("enter the number1:"))
s.add(a)
b = int(input("enter the number2:"))
s.add(b)
c = int(input("enter the number3:"))    
s.add(c)    
d = int(input("enter the number4:"))
s.add(d)
e = int(input("enter the number5:"))
s.add(e)
f = int(input("enter the number6:"))
s.add(f)
g = int(input("enter the number7:"))
s.add(g)
h = int(input("enter the number8:"))
s.add(h)
print(f"The uniq numbers are: {s}")